Profile and SignIn View
dominicrutk/cs326-project pull request #35
Opened 2024-04-20 03:57 UTC by thuphan1312

Hi,

This pull request comes with a Profile Page and Sign In Page. I decided to include a Sign In page even though it was not a part of the To-Do list because the Profile page felt very wrong without Sign In.

All values are hard coded. I have removed my past attempts with PouchDB. My apologies, I didn't understand the requirements of this milestone. I hope to be able to use my 2 days of work in the future in some ways.

This PR is big because it includes both base and CSS Styling for the parts I did and shared parts (header image, h1, button, and form... even though I believe we won't be seeing any other forms than SignIn and Profile Edit). I was in a rabbit hole for a few days but I am learning, that's what's important!

2024-04-20 22:17 UTC, dominicrutk requested changes
Seems good overall. Mostly nitpicky changes to keep the code clean and follow best practices. The only major thing I'd say is scope your CSS styles to your own code for now. At this time, it's most important to lay the groundwork for the whole application by getting the HTML and JS right, so CSS isn't too important _yet_, and making your styles global is going to create some issues because they'll mess with other people's pages.

Also, make sure to merge the latest changes from `main` into your branch so that you can fix potential merge conflicts.

2024-04-20 22:17 UTC, dominicrutk commented on src/client/css/styles.css
Go ahead and move these styles to a new file like `profile.css` or something, and link it up in the HTML file _after_ `styles.css`. This will help us stay organized a lot better.

Also, I think almost all of these styles should be only applied to elements on the profile + sign in pages. (I.e., assign them to classes/IDs instead of entire elements.) You're right that it's good to have global styles (to maintain consistency across the project), but those global styles should only be what's truly global. This means things like container sizes, colors, fonts, font sizes, etc., but generally not spacing, transitions, borders, alignments, display types, etc. For instance, we don't want all `h1` elements to be `display: inline`, nor do we want all buttons to have `40px` of right/left padding. So I'd say for now, make all these styles only apply to elements on your pages (using classes or IDs). We can consolidate styles later.

2024-04-20 22:17 UTC, dominicrutk commented on src/client/css/styles.css
> +  input {width: 100%;
Make sure to run prettier. I don't think it will allow curly braces like this.

2024-04-20 22:17 UTC, dominicrutk commented on src/client/js/App.js
> +
Remove random new line

2024-04-20 22:17 UTC, dominicrutk commented on src/client/js/profile.js
> +
Remove extra new line

2024-04-20 22:17 UTC, dominicrutk commented on src/client/js/profile.js
> +
Remove extra new line

2024-04-20 22:17 UTC, dominicrutk commented on src/client/js/profile.js
> +
Remove extra new line

2024-04-20 22:17 UTC, dominicrutk commented on src/client/js/profile.js
> +  //}
Did you mean to remove this?

2024-04-20 22:17 UTC, dominicrutk commented on src/client/css/styles.css
> +
Remove extra new line

2024-04-20 22:17 UTC, dominicrutk commented on src/client/js/profile.js
> +    this.p
`;`

2024-04-20 22:17 UTC, dominicrutk commented on src/client/css/styles.css
> +  margin: 10px 20%;
You probably don't want a 20% margin. This will give wider buttons more margin on the sides, which doesn't really make sense.

2024-04-20 22:17 UTC, dominicrutk commented on src/client/css/styles.css
> +  float:right;
`float` is generally never used in CSS anymore except for the specific case of moving an image to the side within a function of text. I'm guessing you can recreate this behavior but better with flexbox or grid.

2024-04-23 14:38 UTC, thuphan1312 commented on src/client/js/profile.js
> +  //}
Oh yes!

2024-04-23 14:59 UTC, thuphan1312 commented on src/client/css/styles.css
> +  background-color: rgb(33, 71, 78);
I also set a new variable for the dark teal buttons

2024-04-23 18:53 UTC, dominicrutk commented
Superseded by #45

2024-04-23 18:53 UTC, closed without merging